const fs=require('fs'),vm=require('vm'),assert=require('assert');const els=new Map();const elem=()=>({style:{},dataset:{},classList:{toggle(){}},value:'',querySelectorAll:()=>[],showModal(){},close(){}});const document={querySelector:s=>{if(!els.has(s))els.set(s,elem());return els.get(s)},querySelectorAll:()=>[]};const ctx={MutationObserver:class {observe(){}},document,window:{addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},crypto:require('crypto').webcrypto,structuredClone,console,setTimeout,clearTimeout,alert:s=>{throw Error(s)},confirm:()=>true};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..','app.js'),'utf8'),ctx);function run(s){return vm.runInContext(s,ctx)}
assert.equal(run("monday('2026-09-13')"),'2026-09-07');assert.equal(run("validDate('2026-02-30')"),false);
run(`db={version:1,brands:['A'],tags:['ヘッド'],products:[{id:'p',name:'商品,"改行\\nテスト',brand:'A',tags:['ヘッド'],stock:5,point:2,target:8,note:'=SUM(1)'}],orders:[],history:[]};validate(db)`);
assert.equal(run("importCSV('products',toCSV('products')).n.products[0].note"),'=SUM(1)');assert.equal(run("importCSV('products',toCSV('products')).n.products[0].name"),'商品,"改行\nテスト');run("week='2020-01-06';record('p','2')");assert.equal(run('db.products[0].stock'),5);assert.equal(run('db.history[0].qty'),2);run("week=monday(today());record('p','3')");assert.equal(run('db.products[0].stock'),3);assert.equal(run('db.history.length'),2);run("record('p','4')");assert.equal(run('db.history.length'),2);assert.throws(()=>run("int('-1')"));assert.throws(()=>run("validate({...db,history:[{productId:'missing',week:'2020-01-06',qty:2}]})"));assert.throws(()=>run("parseCSV('a,\"unclosed')"));
run(`db.orders=[{id:'o',productId:'p',name:'商品',brand:'A',tags:['ヘッド'],qty:5,received:0,date:today(),due:'',status:'発注済み',note:''}];modal=(html,save)=>{globalThis.saveModal=save};receive('o');saveModal({get:()=> '2',has:()=>true})`);assert.equal(run('db.products[0].stock'),6);assert.equal(run('db.orders[0].status'),'一部入荷');run("receive('o');saveModal({get:()=> '3',has:()=>true})");assert.equal(run('db.products[0].stock'),9);assert.equal(run('db.orders[0].status'),'入荷済み');run("receive('o')");assert.throws(()=>run("saveModal({get:()=> '1',has:()=>true})"));assert.equal(run('db.products[0].stock'),9);run('validate(db)');console.log('PASS: dates, CSV escaping/roundtrip, validation, historical/current week recording, update uniqueness, partial/full receipts and duplicate protection');
run(`db.products=['a','b','c','d'].map(id=>({id,name:id,brand:'',tags:[],stock:0,point:0,target:0,note:''}));db.orders=[];db.history=[];filters.sort='manual';moveProduct('c',-1,['a','b','c','d'])`);
assert.equal(run("db.products.map(p=>p.id).join('')"),'acbd');
run("moveProduct('a',1,['a','d'])");assert.equal(run("db.products.map(p=>p.id).join('')"),'dcba');
run("moveProduct('d',-1,['d','c','b','a'])");assert.equal(run("db.products.map(p=>p.id).join('')"),'dcba');
run("filters.sort='name';moveProduct('d',1,['d','c','b','a'])");assert.equal(run("db.products.map(p=>p.id).join('')"),'dcba');
assert.equal(run("validate(JSON.parse(JSON.stringify(db))).products.map(p=>p.id).join('')"),'dcba');
console.log('PASS: manual movement, filtered movement, boundaries, alternate sort guard and JSON order retention');
